version: 2
jobs:
  build:
    machine: true
    working_directory: ~/build
    steps:
      - checkout
      - run: curl -fsSL get.nextflow.io | bash
      - run: ./nextflow run . -with-docker --refs=false --trees=false
      - run: ./nextflow run . -with-docker --trees=false
      - run: ./nextflow run . -with-docker --trees='./tutorial/trees/*.dnd'
