version: 2
jobs:
  build:
    machine: true
    working_directory: ~/build
    steps:
      - checkout
      - run: curl -fsSL get.nextflow.io | bash
  mode1:
    machine: true
    working_directory: ~/build
    steps:
      - run: ./nextflow run . -with-docker --refs=false --trees=false
  mode2:
    machine: true
    working_directory: ~/build
    steps:
      - run: ./nextflow run . -with-docker --trees=false
  mode3:
    machine: true
    working_directory: ~/build
    steps:
      - run: ./nextflow run . -with-docker --refs=false --trees='./tutorial/trees/*.dnd'
  mode4:
    machine: true
    working_directory: ~/build
    steps:
      - run: ./nextflow run . -with-docker --trees='./tutorial/trees/*.dnd'
workflows:
  version: 2
  build-test-all-modes:
    jobs:
      - build
      - mode1:
          requires:
            - build
      - mode2:
          requires:
            - build
      - mode3:
          requires:
            - build
      - mode4:
          requires:
            - build
