version: 2
jobs:
  build:
    machine: true
    working_directory: ~/build
    steps:
      - checkout
      - run: curl -fsSL get.nextflow.io | bash
      - run: ./nextflow run . -with-docker

dependencies:
  override:
    - bundle install: # note the colon here
        timeout: 2400
